/rob_1/controller_manager:
  ros__parameters:
    diagnostic_updater:
      period: 1.0
      use_fqn: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    rob_1/integral_sliding_mode_controller:
      type: velocity_controllers/IntegralSlidingModeController
    rob_1/thruster1_controller:
      type: thruster_controllers/PolynomialThrustCurveController
    rob_1/thruster2_controller:
      type: thruster_controllers/PolynomialThrustCurveController
    rob_1/thruster3_controller:
      type: thruster_controllers/PolynomialThrustCurveController
    rob_1/thruster4_controller:
      type: thruster_controllers/PolynomialThrustCurveController
    rob_1/thruster5_controller:
      type: thruster_controllers/PolynomialThrustCurveController
    rob_1/thruster6_controller:
      type: thruster_controllers/PolynomialThrustCurveController
    rob_1/thruster7_controller:
      type: thruster_controllers/PolynomialThrustCurveController
    rob_1/thruster8_controller:
      type: thruster_controllers/PolynomialThrustCurveController
    rob_1/thruster_allocation_matrix_controller:
      type: thruster_allocation_matrix_controller/ThrusterAllocationMatrixController
    start_type_description_service: true
    update_rate: 100
    use_sim_time: false

