mavros:
  ros__parameters:
    system_id: 255
    plugin_allowlist:
      - sys_status
      - command
      - rc_io
      - param

mavros_node:
  ros__parameters:
    fcu_url: "udp://:14550@127.0.0.1:14549"
    gcs_url: "udp://:14549@127.0.0.1:14548"
